[package]
name = "type_cast"
version = "0.1.0"
authors = ["Ilias Makhiyanov <iliasmach@cloud-mind.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
